### ISSUE TITLE
Regenerating the DBusInterfaces.cs File

### ISSUE THREAD

**Issue by aolszowka** [vestervang/DotNet-BlueZ#4] opened 2023-03-24 16:33 UTC
The `DBusInterfaces.cs` contains the `Tmds.DBus.Tool` generated interfaces for the `org.bluez` DBus. This is really a generated file and as per the documentation from the original project:

```csharp
// This file was generated by Tmds.DBus.Tool.
// Bluetoothctl was used to connect to a Bluetooth Low Energy device, then `dotnet dbus codegen --bus system --service org.bluez` was executed.
// After code generation, some `ObjectPath`s were manually replaced with the right interface types.
// For more context, see https://developers.redhat.com/blog/2017/09/18/connecting-net-core-d-bus/ or https://github.com/tmds/Tmds.DBus
```

This branch appears to have regenerated the file at some point, but then ran some type of formatting over it.

We need to regenerate this file to get the latest DBus Interfaces as well as remove some of the experimental/deprecated features that have been removed from the API (See https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc) for example the MediaControl endpoint was deprecated (See https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/media-api.txt) but is still in the DBusInterface.cs as this was generated over 4 years ago.

To make matters more complicated, based on my understanding, this will change based on what platform we're targeting as well as the kernel and userspace we have. For example while the official documentation mentions interfaces such as [AdvertisementMonitor1](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/advertisement-monitor-api.txt) or [MediaPlayer1](https://git.kernel.org/pub/scm/bluetooth/bluez.git/tree/doc/media-api.txt) but running the generator step (`dotnet dbus codegen --bus system --service org.bluez`) on my Raspberry Pi 4B (`uname -a`: Linux rbpi4b 5.15.0-1025-raspi #27-Ubuntu SMP PREEMPT Thu Feb 16 17:09:55 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux / `bluetoothctl -v`: bluetoothctl: 5.64) does not generate those interfaces.

Does anyone have experience with this? Should I submit a PR to target this? (the diff is ugly as all get out!)

**Comment by vestervang** [comment] 2023-03-24 21:12
We could stitch the missing methods by hand. I did that with a experimental feature in the past.

**Comment by aolszowka** [comment] 2023-03-28 01:54
Might be worth a shot; I've been able to make more progress on my project and have worked around not having the AdvertisementMonitor interface so I've abandoned this for now.

I do believe I've found another bug with this library that isn't present in the original one; I'll open up a new issue.

**Comment by vestervang** [comment] 2024-01-05 06:06
I think the problem is that my computer can't find the "AdvertisementMonitor" in blueZ as i might not be supported on my bluetooth chip? I dunno. If the problem arises again feel free to generate the file on your computer and create a PR. I'll close this issue for now.

**Closed as completed by vestervang** 2024-01-05 06:06 UTC
